### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by gephaistos** [liborty/medians#4]
Hello!
After update from 3.0.5 to 3.0.6 I'm getting build errors in my project like:
```
error[E0599]: no function or associated item named `part` found for mutable reference `&mut [T]` in the current scope
   --> /.cargo/registry/src/index.crates.io-6f17d22bba15001f/medians-3.0.6/src/algos.rs:149:42
    |
149 |         let (eqsub, gtsub) = <&mut [T]>::part(s, &rng, c);
    |                                          ^^^^ function or associated item not found in `&mut [T]`
```
and
```
error[E0599]: no method named `ref_vec` found for reference `&[f64]` in the current scope
   --> /.cargo/registry/src/index.crates.io-6f17d22bba15001f/medians-3.0.6/src/lib.rs:144:26
    |
144 |         let mut s = self.ref_vec(0..self.len());
    |                          ^^^^^^^ method not found in `&[f64]`
```
Updating `indxvec` manually to 1.8.9 fixes the problem, I suspect that features necessary for 3.0.6 were added in 1.8.9.
Looks like it is not updated automatically when bumping `medians` version, so I guess that Cargo.toml should use "1.8.9" for `indxvec` as the crate wouldn't compile with earlier "1.8.x" versions.

**Comment by liborty** [comment]
Plain "1.8" in Cargo.toml  should automatically use the latest minor version. That is what I do.
In case of persisting problems, 'cargo update' will then bump up to the latest version.

**Comment by Shatur** [comment]
> Plain "1.8" in Cargo.toml should automatically use the latest minor version. 

While this solves the problem, you need to specify minimum required version `Cargo.toml`. I.e. if you require a feature from `1.8.9`, you should use `indxvec = "1.8.9"`.

Using `indxvec = "1.8"` means that "my crate works with any `indexvec 1.8.x`, but it's not the case.

**Comment by liborty** [comment]
Thanks, I have changed it as you suggest in the github repository for now. The next medians release on crates.io, which will be version 3.0.7, will have it too.
